### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Mishasama** [YEWl/feedbro-locale#8]
No more updates?

**Comment by nkh0472** [comment]
I‘ll not say that.

The translation template embedded in `Feedbro` has not been updated since October 2019. However, the `Feedbro` itself never stops updating.

I have also been puzzled by this situation. 

Anyway, I still regularly check whether the translation template changes. So, this repo is always updated.

**Comment by Mishasama** [comment]
> Anyway, I still regularly check whether the translation template changes. So, this repo is always updated.

What about do some polish? It looks a lot machine translate.
![image](https://user-images.githubusercontent.com/54498172/190397104-8c5ddc6f-9b6e-4637-831c-c92fa119170e.png)

**Comment by nkh0472** [comment]
> What about do some polish? It looks a lot machine translate. ![image](https://user-images.githubusercontent.com/54498172/190397104-8c5ddc6f-9b6e-4637-831c-c92fa119170e.png)

Looks funny. The repo owner uploaded it in 2019.
But these annoying things never can be fixed all……
You can pull a request or you wanna fix it by me?

**Comment by Mishasama** [comment]
> Looks funny. The repo owner uploaded it in 2019. But these annoying things never can be fixed all…… You can pull a request or you wanna fix it by me?

Sorry, I don't have time to polish all problems. If you have some time, it would be nice.

**Comment by nkh0472** [comment]
Fixed in 511bbea758142613371f2b48a25d30e6b429e523
Also improved issue #4 

---
请确保在输入正确的订阅URL后，点击”更新语言文件“来获取更新后的翻译。
![image](https://user-images.githubusercontent.com/67589323/190911667-5d158f33-bb33-4db3-a7f4-b8682299ac30.png)

订阅链接为：https://raw.githubusercontent.com/YEWl/feedbro-locale/master/feedbro-locale-zh_CN.json
